### ISSUE TITLE
[Idea] Split package names and versions

### ISSUE THREAD

**Issue by dealproc** [brentkrueger/VisualStudio2017PackageVisualizer#11]
Is it possible to adjust the add-in to split between the nuget package name and its version (e.g. Source and SourceVersion; Target and TargetVersion)

It would help to then extend this project to build an excel sheet on it for reporting purposes.

Just a thought.  YMMV and all that cool stuff.

**Comment by brentkrueger** [comment]
I've pretty much put this package on the back burner. I haven't had the time to commit to it. If you, or someone else wanted to take this work on, we could get it reviewed and submitted.

**Comment by dealproc** [comment]
Ok, no worries.  I got enough going that I was ok... I'm going to be chatting with the nuget team to see if we can enhance nuget to do the output from cmd line, so I can do a csv output, to make it easier to chart, etc.
