### ISSUE TITLE
[Idea] Filtering on Namespace

### ISSUE THREAD

**Issue by ColinM9991-zz** [brentkrueger/VisualStudio2017PackageVisualizer#6]
Placing this issue to open discussion around this idea.

Since adding PackageReference support, I have shared this with a team I am on where I work as we have an internal NuGet feed where we hold several of our packages that have inter-dependencies which can be somewhat of a pain for newcomers to see what packages are used and where - primarily in which order to update these packages.

My idea is to introduce an input box which gives you the options to filter on the NuGet packages you want to visualize. When the dgml is created it should then contain only the packages which you filtered on and thus removes some of the 'noise' such as the Microsoft & System namespaces.

Filtering should be optional, and should maintain backward compatibility (I.E: No filter returns all packages)

@brentkrueger what are your thoughts on this? Does the problem & goal seem clear?

**Comment by daghb** [comment]
Second that. Would be a terrific enhancement. I am in the same situation.

**Comment by brentkrueger** [comment]
I also think that sounds like a useful enhancement. I would be fine if someone wanted to take on that work. Thank you!

**Comment by ColinM9991-zz** [comment]
I'll get up to speed on VSIX extension development over this weekend and will begin implementing this functionality with possibly a simple textbox as a minimum viable solution.

**Comment by daghb** [comment]
If it is possible and not much of an extra hassle, please make the text regex aware, @ColinM9991.
