### ISSUE TITLE
Solution consists of 10-15 projects, but only two are analyzed

### ISSUE THREAD

**Issue by daghb** [brentkrueger/VisualStudio2017PackageVisualizer#8]
The rest of the projects are left as standalone blue boxes in the DGML viewer without any connections flowing out of these.

**Comment by ColinM9991-zz** [comment]
Hi @daghb 

Could you provide more context on this issue?

* What version of Visual studio is used?
* Are the projects using `PackageReference` or `packages.config` for NuGet?

More importantly, are you using the latest version of this extension, built locally and installed?
I added `PackageReference` support, but as no release exists for this then you'll have to build locally and install.

**Comment by daghb** [comment]
Thank you for responding, @ColinM9991.

You're right - those two project were not using PackageReference but packages.config. The rest of the projects are using PackageReference. However, the .vsix file was built locally using the latest sources. I tried today on another computer today with the same result.

* Visual Studio 2017 Pro 15.3.5 (latest official version)

See enclosed example .csproj of project not loading (Anonymized)
[Anonymized.csproj.txt](https://github.com/brentkrueger/VisualStudio2017PackageVisualizer/files/1366767/Anonymized.csproj.txt)

**Comment by ColinM9991-zz** [comment]
This is interesting as I have encountered no problems with my solutions which use both PackageReference & packages.config, to find out more I'd suggest debugging the PackageVisualizer solution.

To debug the solution you can do the following.

1. Uninstall the existing VSIX extension
2. Open the PackageVisualizer solution
3. Open the 'Properties' window of the PackageVisualizer project
4. Under 'Debug', choose 'Start external program' and browse to the VS 2017 devenv.exe path
5. Set the Command line arguments to `/rootsuffix Exp`
6. Add the following attribute to the `VisualizerCommandPackage` class `[ProvideAutoLoad(UIContextGuids.NoSolution)]`
7. Start the debugger, and open your solution in the newly opened Visual Studio instance

With this done, you should be able to step through the code and see exactly what's going on in the `LoadPackageReferenceConfigs` method.

**Comment by daghb** [comment]
Thanks, found the bug. The XML namespace wasn't used in the inner foreach of the LoadPackageConfig method.

Replace

```
foreach (var pr in XDocument.Load(pk).Descendants(packageElementName))
```

with

```
var doc = XDocument.Load(pk);
foreach (var pr in doc?.Descendants(doc.Root.Name.Namespace + packageElementName))
```
